package br.com.nucleo.api.audit.domain;

public enum AuditResourceType {

    USER,
    FAMILY,
    FAMILY_MEMBERSHIP,
    FAMILY_INVITATION,

    AGENDA_EVENT,
    AGENDA_OCCURRENCE,

    SHOPPING_LIST,
    SHOPPING_ITEM,

    FINANCIAL_ACCOUNT,
    FINANCIAL_CATEGORY,
    FINANCIAL_TRANSACTION,
    FINANCIAL_RECURRENCE,
    FINANCIAL_BUDGET,
    FINANCIAL_CREDIT_CARD,
    FINANCIAL_CREDIT_CARD_PURCHASE,
    FINANCIAL_CREDIT_CARD_INVOICE,

    NOTIFICATION,
    NOTIFICATION_PREFERENCE,

    SYSTEM
}