package br.com.nucleo.api.notification.domain;

public enum NotificationType {

    FAMILY_INVITATION,
    FAMILY_MEMBER_JOINED,
    FAMILY_ROLE_CHANGED,

    AGENDA_EVENT_CREATED,
    AGENDA_EVENT_UPDATED,
    AGENDA_REMINDER,

    SHOPPING_LIST_UPDATED,
    SHOPPING_ITEM_ADDED,

    FINANCIAL_BUDGET_ALERT,
    FINANCIAL_TRANSACTION_DUE,
    FINANCIAL_RECURRENCE_CONFIRMATION,
    CREDIT_CARD_INVOICE_DUE,

    SYSTEM
}
